export const countries = [
  "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda",
  "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain",
  "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan",
  "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria",
  "Burkina Faso", "Burundi", "Cambodia", "Cameroon", "Canada", "Cape Verde",
  "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros",
  "Congo", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czech Republic", "Denmark",
  "Djibouti", "Dominica", "Dominican Republic", "East Timor", "Ecuador", "Egypt",
  "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Fiji",
  "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece",
  "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras",
  "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel",
  "Italy", "Ivory Coast", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya",
  "Kiribati", "North Korea", "South Korea", "Kosovo", "Kuwait", "Kyrgyzstan", "Laos",
  "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania",
  "Luxembourg", "Macedonia", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali",
  "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia",
  "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar",
  "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger",
  "Nigeria", "Norway", "Oman", "Pakistan", "Palau", "Palestine", "Panama",
  "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal",
  "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia",
  "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe",
  "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore",
  "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Sudan",
  "Spain", "Sri Lanka", "Sudan", "Suriname", "Swaziland", "Sweden", "Switzerland",
  "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Togo", "Tonga",
  "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda",
  "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay",
  "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela", "Vietnam", "Yemen", "Zambia",
  "Zimbabwe"
];

export const countryPhoneCodes: Record<string, string> = {
  "Afghanistan": "+93",
  "Albania": "+355",
  "Algeria": "+213",
  "Andorra": "+376",
  "Angola": "+244",
  "Antigua and Barbuda": "+1268",
  "Argentina": "+54",
  "Armenia": "+374",
  "Australia": "+61",
  "Austria": "+43",
  "Azerbaijan": "+994",
  "Bahamas": "+1242",
  "Bahrain": "+973",
  "Bangladesh": "+880",
  "Barbados": "+1246",
  "Belarus": "+375",
  "Belgium": "+32",
  "Belize": "+501",
  "Benin": "+229",
  "Bhutan": "+975",
  "Bolivia": "+591",
  "Bosnia and Herzegovina": "+387",
  "Botswana": "+267",
  "Brazil": "+55",
  "Brunei": "+673",
  "Bulgaria": "+359",
  "Burkina Faso": "+226",
  "Burundi": "+257",
  "Cambodia": "+855",
  "Cameroon": "+237",
  "Canada": "+1",
  "Cape Verde": "+238",
  "Central African Republic": "+236",
  "Chad": "+235",
  "Chile": "+56",
  "China": "+86",
  "Colombia": "+57",
  "Comoros": "+269",
  "Congo": "+242",
  "Costa Rica": "+506",
  "Croatia": "+385",
  "Cuba": "+53",
  "Cyprus": "+357",
  "Czech Republic": "+420",
  "Denmark": "+45",
  "Djibouti": "+253",
  "Dominica": "+1767",
  "Dominican Republic": "+1809",
  "East Timor": "+670",
  "Ecuador": "+593",
  "Egypt": "+20",
  "El Salvador": "+503",
  "Equatorial Guinea": "+240",
  "Eritrea": "+291",
  "Estonia": "+372",
  "Ethiopia": "+251",
  "Fiji": "+679",
  "Finland": "+358",
  "France": "+33",
  "Gabon": "+241",
  "Gambia": "+220",
  "Georgia": "+995",
  "Germany": "+49",
  "Ghana": "+233",
  "Greece": "+30",
  "Grenada": "+1473",
  "Guatemala": "+502",
  "Guinea": "+224",
  "Guinea-Bissau": "+245",
  "Guyana": "+592",
  "Haiti": "+509",
  "Honduras": "+504",
  "Hungary": "+36",
  "Iceland": "+354",
  "India": "+91",
  "Indonesia": "+62",
  "Iran": "+98",
  "Iraq": "+964",
  "Ireland": "+353",
  "Israel": "+972",
  "Italy": "+39",
  "Ivory Coast": "+225",
  "Jamaica": "+1876",
  "Japan": "+81",
  "Jordan": "+962",
  "Kazakhstan": "+7",
  "Kenya": "+254",
  "Kiribati": "+686",
  "North Korea": "+850",
  "South Korea": "+82",
  "Kosovo": "+383",
  "Kuwait": "+965",
  "Kyrgyzstan": "+996",
  "Laos": "+856",
  "Latvia": "+371",
  "Lebanon": "+961",
  "Lesotho": "+266",
  "Liberia": "+231",
  "Libya": "+218",
  "Liechtenstein": "+423",
  "Lithuania": "+370",
  "Luxembourg": "+352",
  "Macedonia": "+389",
  "Madagascar": "+261",
  "Malawi": "+265",
  "Malaysia": "+60",
  "Maldives": "+960",
  "Mali": "+223",
  "Malta": "+356",
  "Marshall Islands": "+692",
  "Mauritania": "+222",
  "Mauritius": "+230",
  "Mexico": "+52",
  "Micronesia": "+691",
  "Moldova": "+373",
  "Monaco": "+377",
  "Mongolia": "+976",
  "Montenegro": "+382",
  "Morocco": "+212",
  "Mozambique": "+258",
  "Myanmar": "+95",
  "Namibia": "+264",
  "Nauru": "+674",
  "Nepal": "+977",
  "Netherlands": "+31",
  "New Zealand": "+64",
  "Nicaragua": "+505",
  "Niger": "+227",
  "Nigeria": "+234",
  "Norway": "+47",
  "Oman": "+968",
  "Pakistan": "+92",
  "Palau": "+680",
  "Palestine": "+970",
  "Panama": "+507",
  "Papua New Guinea": "+675",
  "Paraguay": "+595",
  "Peru": "+51",
  "Philippines": "+63",
  "Poland": "+48",
  "Portugal": "+351",
  "Qatar": "+974",
  "Romania": "+40",
  "Russia": "+7",
  "Rwanda": "+250",
  "Saint Kitts and Nevis": "+1869",
  "Saint Lucia": "+1758",
  "Saint Vincent and the Grenadines": "+1784",
  "Samoa": "+685",
  "San Marino": "+378",
  "Sao Tome and Principe": "+239",
  "Saudi Arabia": "+966",
  "Senegal": "+221",
  "Serbia": "+381",
  "Seychelles": "+248",
  "Sierra Leone": "+232",
  "Singapore": "+65",
  "Slovakia": "+421",
  "Slovenia": "+386",
  "Solomon Islands": "+677",
  "Somalia": "+252",
  "South Africa": "+27",
  "South Sudan": "+211",
  "Spain": "+34",
  "Sri Lanka": "+94",
  "Sudan": "+249",
  "Suriname": "+597",
  "Swaziland": "+268",
  "Sweden": "+46",
  "Switzerland": "+41",
  "Syria": "+963",
  "Taiwan": "+886",
  "Tajikistan": "+992",
  "Tanzania": "+255",
  "Thailand": "+66",
  "Togo": "+228",
  "Tonga": "+676",
  "Trinidad and Tobago": "+1868",
  "Tunisia": "+216",
  "Turkey": "+90",
  "Turkmenistan": "+993",
  "Tuvalu": "+688",
  "Uganda": "+256",
  "Ukraine": "+380",
  "United Arab Emirates": "+971",
  "United Kingdom": "+44",
  "United States": "+1",
  "Uruguay": "+598",
  "Uzbekistan": "+998",
  "Vanuatu": "+678",
  "Vatican City": "+379",
  "Venezuela": "+58",
  "Vietnam": "+84",
  "Yemen": "+967",
  "Zambia": "+260",
  "Zimbabwe": "+263"
};

export const getCountryPhoneCode = (country: string): string => {
  return countryPhoneCodes[country] || "";
};

// Phone number length limits per country (local number length, excluding country code)
export const countryPhoneLengths: Record<string, { min: number; max: number }> = {
  "Afghanistan": { min: 9, max: 9 },
  "Albania": { min: 9, max: 9 },
  "Algeria": { min: 9, max: 9 },
  "Andorra": { min: 6, max: 9 },
  "Angola": { min: 9, max: 9 },
  "Argentina": { min: 10, max: 10 },
  "Armenia": { min: 8, max: 8 },
  "Australia": { min: 9, max: 9 },
  "Austria": { min: 10, max: 13 },
  "Azerbaijan": { min: 9, max: 9 },
  "Bahamas": { min: 7, max: 7 },
  "Bahrain": { min: 8, max: 8 },
  "Bangladesh": { min: 10, max: 10 },
  "Barbados": { min: 7, max: 7 },
  "Belarus": { min: 9, max: 9 },
  "Belgium": { min: 8, max: 9 },
  "Brazil": { min: 10, max: 11 },
  "Bulgaria": { min: 8, max: 9 },
  "Burundi": { min: 8, max: 8 },
  "Cambodia": { min: 8, max: 9 },
  "Cameroon": { min: 9, max: 9 },
  "Canada": { min: 10, max: 10 },
  "Chile": { min: 9, max: 9 },
  "China": { min: 11, max: 11 },
  "Colombia": { min: 10, max: 10 },
  "Congo": { min: 9, max: 9 },
  "Costa Rica": { min: 8, max: 8 },
  "Croatia": { min: 8, max: 9 },
  "Cuba": { min: 8, max: 8 },
  "Cyprus": { min: 8, max: 8 },
  "Czech Republic": { min: 9, max: 9 },
  "Denmark": { min: 8, max: 8 },
  "Dominican Republic": { min: 10, max: 10 },
  "Ecuador": { min: 9, max: 9 },
  "Egypt": { min: 10, max: 10 },
  "El Salvador": { min: 8, max: 8 },
  "Eritrea": { min: 7, max: 7 },
  "Estonia": { min: 7, max: 8 },
  "Ethiopia": { min: 9, max: 9 },
  "Fiji": { min: 7, max: 7 },
  "Finland": { min: 9, max: 10 },
  "France": { min: 9, max: 9 },
  "Gabon": { min: 7, max: 8 },
  "Gambia": { min: 7, max: 7 },
  "Georgia": { min: 9, max: 9 },
  "Germany": { min: 10, max: 11 },
  "Ghana": { min: 9, max: 9 },
  "Greece": { min: 10, max: 10 },
  "Guatemala": { min: 8, max: 8 },
  "Haiti": { min: 8, max: 8 },
  "Honduras": { min: 8, max: 8 },
  "Hungary": { min: 9, max: 9 },
  "Iceland": { min: 7, max: 7 },
  "India": { min: 10, max: 10 },
  "Indonesia": { min: 9, max: 12 },
  "Iran": { min: 10, max: 10 },
  "Iraq": { min: 10, max: 10 },
  "Ireland": { min: 9, max: 9 },
  "Israel": { min: 9, max: 9 },
  "Italy": { min: 9, max: 10 },
  "Ivory Coast": { min: 8, max: 8 },
  "Jamaica": { min: 7, max: 7 },
  "Japan": { min: 10, max: 10 },
  "Jordan": { min: 9, max: 9 },
  "Kazakhstan": { min: 10, max: 10 },
  "Kenya": { min: 9, max: 9 },
  "Kuwait": { min: 8, max: 8 },
  "Latvia": { min: 8, max: 8 },
  "Lebanon": { min: 7, max: 8 },
  "Liberia": { min: 7, max: 8 },
  "Libya": { min: 9, max: 9 },
  "Lithuania": { min: 8, max: 8 },
  "Luxembourg": { min: 9, max: 9 },
  "Madagascar": { min: 9, max: 9 },
  "Malawi": { min: 9, max: 9 },
  "Malaysia": { min: 9, max: 10 },
  "Maldives": { min: 7, max: 7 },
  "Mali": { min: 8, max: 8 },
  "Malta": { min: 8, max: 8 },
  "Mauritius": { min: 8, max: 8 },
  "Mexico": { min: 10, max: 10 },
  "Moldova": { min: 8, max: 8 },
  "Monaco": { min: 8, max: 9 },
  "Mongolia": { min: 8, max: 8 },
  "Montenegro": { min: 8, max: 8 },
  "Morocco": { min: 9, max: 9 },
  "Mozambique": { min: 9, max: 9 },
  "Myanmar": { min: 8, max: 10 },
  "Namibia": { min: 9, max: 9 },
  "Nepal": { min: 10, max: 10 },
  "Netherlands": { min: 9, max: 9 },
  "New Zealand": { min: 8, max: 9 },
  "Nicaragua": { min: 8, max: 8 },
  "Niger": { min: 8, max: 8 },
  "Nigeria": { min: 10, max: 10 },
  "North Korea": { min: 8, max: 9 },
  "Norway": { min: 8, max: 8 },
  "Oman": { min: 8, max: 8 },
  "Pakistan": { min: 10, max: 10 },
  "Palestine": { min: 9, max: 9 },
  "Panama": { min: 8, max: 8 },
  "Paraguay": { min: 9, max: 9 },
  "Peru": { min: 9, max: 9 },
  "Philippines": { min: 10, max: 10 },
  "Poland": { min: 9, max: 9 },
  "Portugal": { min: 9, max: 9 },
  "Qatar": { min: 8, max: 8 },
  "Romania": { min: 9, max: 9 },
  "Russia": { min: 10, max: 10 },
  "Rwanda": { min: 9, max: 9 },
  "Saudi Arabia": { min: 9, max: 9 },
  "Senegal": { min: 9, max: 9 },
  "Serbia": { min: 8, max: 9 },
  "Sierra Leone": { min: 8, max: 8 },
  "Singapore": { min: 8, max: 8 },
  "Slovakia": { min: 9, max: 9 },
  "Slovenia": { min: 8, max: 8 },
  "Somalia": { min: 7, max: 8 },
  "South Africa": { min: 9, max: 9 },
  "South Korea": { min: 9, max: 10 },
  "South Sudan": { min: 9, max: 9 },
  "Spain": { min: 9, max: 9 },
  "Sri Lanka": { min: 9, max: 9 },
  "Sudan": { min: 9, max: 9 },
  "Swaziland": { min: 8, max: 8 },
  "Sweden": { min: 9, max: 9 },
  "Switzerland": { min: 9, max: 9 },
  "Syria": { min: 9, max: 9 },
  "Taiwan": { min: 9, max: 9 },
  "Tajikistan": { min: 9, max: 9 },
  "Tanzania": { min: 9, max: 9 },
  "Thailand": { min: 9, max: 9 },
  "Togo": { min: 8, max: 8 },
  "Tunisia": { min: 8, max: 8 },
  "Turkey": { min: 10, max: 10 },
  "Turkmenistan": { min: 8, max: 8 },
  "Uganda": { min: 9, max: 9 },
  "Ukraine": { min: 9, max: 9 },
  "United Arab Emirates": { min: 9, max: 9 },
  "United Kingdom": { min: 10, max: 10 },
  "United States": { min: 10, max: 10 },
  "Uruguay": { min: 8, max: 8 },
  "Uzbekistan": { min: 9, max: 9 },
  "Venezuela": { min: 10, max: 10 },
  "Vietnam": { min: 9, max: 10 },
  "Yemen": { min: 9, max: 9 },
  "Zambia": { min: 9, max: 9 },
  "Zimbabwe": { min: 9, max: 9 },
};

export const getPhoneLimits = (country: string): { min: number; max: number } => {
  return countryPhoneLengths[country] || { min: 7, max: 15 };
};

export const validatePhoneLength = (country: string, localNumber: string): { valid: boolean; message: string } => {
  const limits = getPhoneLimits(country);
  const digits = localNumber.replace(/\D/g, '');
  
  if (digits.length === 0) {
    return { valid: true, message: '' }; // Empty is valid (optional)
  }
  if (digits.length < limits.min) {
    return { valid: false, message: `Need ${limits.min} digits` };
  }
  if (digits.length > limits.max) {
    return { valid: false, message: `Max ${limits.max} digits` };
  }
  return { valid: true, message: '' };
};

// Function to detect user's country from browser (requires geolocation API or IP lookup)
export const detectUserCountry = async (): Promise<string | null> => {
  try {
    // Using a free IP geolocation service
    const response = await fetch('https://ipapi.co/json/');
    const data = await response.json();
    return data.country_name || null;
  } catch (error) {
    console.error('Error detecting country:', error);
    return null;
  }
};
